### ISSUE TITLE
JPush-iOS-SDK (1.8.3)` which has a minimum requirement of iOS 8.0

### ISSUE THREAD

**Issue by wanyakun** [iosmvn/JPush-iOS-SDK#1]
官方是5.0以上，这里是否可以修改下。

**Comment by danfeng** [comment]
已修改好，谢谢指出！

在 2015-05-15 12:00:51，"wanyakun" notifications@github.com 写道：

官方是5.0以上，这里是否可以修改下。

**Comment by wanyakun** [comment]
README中  pod "JPush-iOS-SDK" 这里应该为单引号。

**Comment by danfeng** [comment]
已修改好，支持5.0需要先执行pod setup。
