### ISSUE TITLE
cocoapods导入后，运行找不到静态库

### ISSUE THREAD

**Issue by chaosVoid** [iosmvn/JPush-iOS-SDK#4]
ld: library not found for -ljpush-ios-2.1.6
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by danfeng** [comment]
pod 'JPush-iOS-SDK', '~> 2.1.8'

检测下。
target 'targetName' do
end

**Comment by chaosVoid** [comment]
非常感谢回复。
当时的cocoaPods的版本是0.39.0。
目前已经换Jpush使用了。
大神你的这个名字太误导了，我开始还以为是官方的。

**Comment by danfeng** [comment]
官方的不是最新的，没做任何改动。
