### ISSUE TITLE
你好，pod未更新 搜不到你的2.1.8

### ISSUE THREAD

**Issue by aquilx** [iosmvn/JPush-iOS-SDK#5]
-> JPush-iOS-SDK (1.8.8)
   JPush SDK for
   iOS.极光推送，使得开发者可以即时地向其应用程序的用户推送通知或者消息，与用户保持互动，从而有效地提高留存率，提升用户体验。平台提供整合了Android推送、iOS推送的统一推送服务。
   pod 'JPush-iOS-SDK', '~> 1.8.8'
- Homepage: http://www.jpush.cn/
- Source:   https://github.com/iosmvn/JPush-iOS-SDK.git
- Versions: 1.8.8, 1.8.7, 1.8.5, 1.8.4, 1.8.3.1, 1.8.3 [master repo]

**Comment by danfeng** [comment]
-> JPush-iOS-SDK (2.1.8)
   JPush SDK for
   iOS.极光推送，使得开发者可以即时地向其应用程序的用户推送通知或者消息，与用户
保持互动，从而有效地提高留存率，提升用户体验。平台提供整合了Android推送、iOS推送的统一推送服务。
   pod 'JPush-iOS-SDK', '~> 2.1.8'
- Homepage: http://www.jpush.cn/
- Source:   https://github.com/iosmvn/JPush-iOS-SDK.git
- Versions: 2.1.8, 2.1.7, 2.1.6, 2.1.0, 1.8.8, 1.8.7, 1.8.5, 1.8.4, 1.8.3.1,
  1.8.3 [master repo]

**Comment by danfeng** [comment]
执行 pod repo update ，然后再搜索。
