### ISSUE TITLE
Add example to show how to use ?

### ISSUE THREAD

**Issue by jibeex** [iosmvn/JPush-iOS-SDK#6]
Hello, 

thanks for your work. It would be more helpful if you can add an example project to show how to  use this pod.

Jianbin

**Comment by danfeng** [comment]
step1:Ensure pod development environment;
step2:Edit Podfile and write `pod 'JPush-iOS-SDK'`;
step3:Execute command `pod install`;
step4:Replace `#import "JPUSHService.h"` to `#import <JPush-iOS-SDK/JPUSHService.h>`;
step5:ok，code。
